baseURL = "https://salma.sohrabi.dev"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/fontawesome.css"
[[params.plugins.css]]
URL = "css/brands.css"
[[params.plugins.css]]
URL = "css/solid.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

[[menu.header]]
name = "Projects"
URL = "#projects"
weight = 2

[[menu.header]]
name = "Outreach"
URL = "#outreach"
weight = 3

[[menu.header]]
name = "Education"
URL = "#education"
weight = 4

[[menu.header]]
name = "Contact"
URL = "#contact"
weight = 5

[[menu.footer]]
name = "Projects"
URL = "#projects"
weight = 2

[[menu.footer]]
name = "Outreach"
URL = "#outreach"
weight = 3

[[menu.footer]]
name = "Education"
URL = "#education"
weight = 4

[[menu.footer]]
name = "Contact"
URL = "#contact"
weight = 5


[params]

sections = [
  "showcase",
  "about",
  "projects",
  "outreach",
  "education",
  "certifications",
  "experience",
  "testimonial",
  "contact",
  "newsletter",
]

googleTagManagerID = "GTM-52QJ8QC" # Google Analytics works with Google Tag Manager

[params.logo]
text1 = "Salma"
text2 = "Sohrabi-Jahromi"

[params.footer]
copyright = "© 2024 Salma Sohrabi-Jahromi."
