[project]
authors = ["Salma Sohrabi-Jahromi"]
channels = ["conda-forge"]
description = "My personal website"
name = "sohrabi_dev"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
lint = "pre-commit run --all-files"
install-precommit = "pre-commit install"
run-hugo = "hugo server"

[dependencies]
python = ">=3.9"
pre-commit = "*"
taplo = ">=0.9.3,<0.10"
hugo = ">=0.139.5,<0.140"
